/** @type {import('tailwindcss').Config} */
const {
  black,
  white,
  gray,
  emerald,
  indigo,
  yellow,
  red,
  slate,
  zinc,
  neutral,
  stone,
  orange,
  amber,
  lime,
  green,
  teal,
  cyan,
  sky,
  blue,
  primary,
  purple,
  fuchsia,
  pink,
  rose,
  violet,
} = require('tailwindcss/colors')
module.exports = {
  mode: 'jit',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    fontFamily: {
      'dm-sans': ["'DM Sans'", 'sans-serif'],
    },
    colors: {
      transparent: 'transparent',
      current: '#101828',
      black: black,
      white: white,
      gray: gray,
      emerald: emerald,
      indigo: indigo,
      yellow: yellow,
      red: red,
      slate: slate,
      zinc: zinc,
      neutral: neutral,
      stone: stone,
      orange: orange,
      amber: amber,
      lime: lime,
      green: green,
      teal: teal,
      cyan: cyan,
      sky: sky,
      blue: blue,
      primary: primary,
      purple: purple,
      fuchsia: fuchsia,
      pink: pink,
      rose: rose,
      violet: violet,
      gray: '#717171',
      'light-gray': '#f2f2f2',
      primary: '#7D23E0',
      ghost: '#9A9AA9',
      cloud: '#fafafb',
      lavender: '#E3CEFA',
      vizard: '#E9E8FF',
      cyan: '#D0EFFF',
      turquoise: '#D1F5F9',
      'light-orange': '#FDEEEE',
      'purple-main': '#7D23E0',
      'grey-border': '#8D8D8D',
      'desc-gray': '#414141',
      deep_red: '#FF3A3A',
      light_red: '#FF5070',
      light_yellow: '#FFD130',
      light_green: '#1CC24A',
      deep_green: '#009E2B',
    },
    extend: {
      boxShadow: {
        '3xl': '0px 2px 40px rgba(125, 35, 224, 0.15)',
        '4xl': '0px 0px 10px rgba(0, 0, 0, 0.15)',
        '5xl': '0px 4px 4px rgba(0, 0, 0, 0.25)',
      },
    },
  },
  plugins: [],
  important: true,
  corePlugins: {
    preflight: true,
  },
}
